services:

  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - ./compose/db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  meilisearch:
    image: getmeili/meilisearch:v1.12
    environment:
      MEILI_MASTER_KEY: a-ArzKFISr1izZ5Ib_zqhIfWGU6x1Vxv4CnaGXFDJ-I
    volumes:
      - ./compose/data.ms:/data.ms
    ports:
      - "7700:7700"

  redis:
      image: redis:7.2.4
      ports:
        - "6379:6379"
      environment:
        REDIS_PORT: 6379
        ALLOW_EMPTY_PASSWORD: yes

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: order-service
    environment:
      LOG_LEVEL: info
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: test
      MEILISEARCH_HOST: meilisearch
      MEILISEARCH_PORT: 7700
      MEILISEARCH_MASTER_KEY: a-ArzKFISr1izZ5Ib_zqhIfWGU6x1Vxv4CnaGXFDJ-I

    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 5s
      timeout: 30s
      retries: 15
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      meilisearch:
        condition: service_started
